# TCL File Generated by Component Editor 18.1
# Sat Sep 28 17:51:17 ICT 2019
# DO NOT MODIFY


# 
# AES "AES" v1.0
#  2019.09.28.17:51:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AES
# 
set_module_property DESCRIPTION ""
set_module_property NAME AES
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AES
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AES_Qsys
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AES.v VERILOG PATH ip/AES/AES.v
add_fileset_file AES_FIFO.v VERILOG PATH ip/AES/AES_FIFO.v
add_fileset_file AES_Qsys.v VERILOG PATH ip/AES/AES_Qsys.v TOP_LEVEL_FILE
add_fileset_file AES_endec.v VERILOG PATH ip/AES/AES_endec.v
add_fileset_file AES_endec_block.v VERILOG PATH ip/AES/AES_endec_block.v
add_fileset_file AES_makekey.v VERILOG PATH ip/AES/AES_makekey.v
add_fileset_file AES_with_buffer_in.v VERILOG PATH ip/AES/AES_with_buffer_in.v
add_fileset_file FIFO.v VERILOG PATH ip/AES/FIFO.v
add_fileset_file FIFO_full.v VERILOG PATH ip/AES/FIFO_full.v
add_fileset_file First_round.v VERILOG PATH ip/AES/First_round.v
add_fileset_file First_round_key.v VERILOG PATH ip/AES/First_round_key.v
add_fileset_file Inverse_MixColumn_round.v VERILOG PATH ip/AES/Inverse_MixColumn_round.v
add_fileset_file Last_round.v VERILOG PATH ip/AES/Last_round.v
add_fileset_file Main_round_key.v VERILOG PATH ip/AES/Main_round_key.v
add_fileset_file Makekey_write_to_RAM.v VERILOG PATH ip/AES/Makekey_write_to_RAM.v
add_fileset_file Multiple_standard_round.v VERILOG PATH ip/AES/Multiple_standard_round.v
add_fileset_file N_divide_6.v VERILOG PATH ip/AES/N_divide_6.v
add_fileset_file SBOX_key_sm_S.v VERILOG PATH ip/AES/SBOX_key_sm_S.v
add_fileset_file Standard_round.v VERILOG PATH ip/AES/Standard_round.v
add_fileset_file ram2port.v VERILOG PATH ip/AES/ram2port.v
add_fileset_file ram_2port.v VERILOG PATH ip/AES/ram_2port.v
add_fileset_file run_on_board.v VERILOG PATH ip/AES/run_on_board.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 4
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock system_clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink iRst_n reset_n Input 1


# 
# connection point master_read
# 
add_interface master_read avalon start
set_interface_property master_read addressUnits SYMBOLS
set_interface_property master_read associatedClock system_clock
set_interface_property master_read associatedReset reset_sink
set_interface_property master_read bitsPerSymbol 8
set_interface_property master_read burstOnBurstBoundariesOnly false
set_interface_property master_read burstcountUnits WORDS
set_interface_property master_read doStreamReads false
set_interface_property master_read doStreamWrites false
set_interface_property master_read holdTime 0
set_interface_property master_read linewrapBursts false
set_interface_property master_read maximumPendingReadTransactions 0
set_interface_property master_read maximumPendingWriteTransactions 0
set_interface_property master_read readLatency 0
set_interface_property master_read readWaitTime 1
set_interface_property master_read setupTime 0
set_interface_property master_read timingUnits Cycles
set_interface_property master_read writeWaitTime 0
set_interface_property master_read ENABLED true
set_interface_property master_read EXPORT_OF ""
set_interface_property master_read PORT_NAME_MAP ""
set_interface_property master_read CMSIS_SVD_VARIABLES ""
set_interface_property master_read SVD_ADDRESS_GROUP ""

add_interface_port master_read iRM_rddatavalid readdatavalid Input 1
add_interface_port master_read iRM_wairequest waitrequest Input 1
add_interface_port master_read iRM_rddata readdata Input DATA_WIDTH
add_interface_port master_read oRM_read read Output 1
add_interface_port master_read oRM_rdaddr address Output DATA_WIDTH


# 
# connection point master_write
# 
add_interface master_write avalon start
set_interface_property master_write addressUnits SYMBOLS
set_interface_property master_write associatedClock system_clock
set_interface_property master_write associatedReset reset_sink
set_interface_property master_write bitsPerSymbol 8
set_interface_property master_write burstOnBurstBoundariesOnly false
set_interface_property master_write burstcountUnits WORDS
set_interface_property master_write doStreamReads false
set_interface_property master_write doStreamWrites false
set_interface_property master_write holdTime 0
set_interface_property master_write linewrapBursts false
set_interface_property master_write maximumPendingReadTransactions 0
set_interface_property master_write maximumPendingWriteTransactions 0
set_interface_property master_write readLatency 0
set_interface_property master_write readWaitTime 1
set_interface_property master_write setupTime 0
set_interface_property master_write timingUnits Cycles
set_interface_property master_write writeWaitTime 0
set_interface_property master_write ENABLED true
set_interface_property master_write EXPORT_OF ""
set_interface_property master_write PORT_NAME_MAP ""
set_interface_property master_write CMSIS_SVD_VARIABLES ""
set_interface_property master_write SVD_ADDRESS_GROUP ""

add_interface_port master_write iWM_waitrequest waitrequest Input 1
add_interface_port master_write oWM_wraddr address Output DATA_WIDTH
add_interface_port master_write oWM_wrdata writedata Output DATA_WIDTH
add_interface_port master_write oWM_write write Output 1


# 
# connection point control_status
# 
add_interface control_status avalon end
set_interface_property control_status addressUnits WORDS
set_interface_property control_status associatedClock system_clock
set_interface_property control_status associatedReset reset_sink
set_interface_property control_status bitsPerSymbol 8
set_interface_property control_status burstOnBurstBoundariesOnly false
set_interface_property control_status burstcountUnits WORDS
set_interface_property control_status explicitAddressSpan 0
set_interface_property control_status holdTime 0
set_interface_property control_status linewrapBursts false
set_interface_property control_status maximumPendingReadTransactions 0
set_interface_property control_status maximumPendingWriteTransactions 0
set_interface_property control_status readLatency 0
set_interface_property control_status readWaitTime 1
set_interface_property control_status setupTime 0
set_interface_property control_status timingUnits Cycles
set_interface_property control_status writeWaitTime 0
set_interface_property control_status ENABLED true
set_interface_property control_status EXPORT_OF ""
set_interface_property control_status PORT_NAME_MAP ""
set_interface_property control_status CMSIS_SVD_VARIABLES ""
set_interface_property control_status SVD_ADDRESS_GROUP ""

add_interface_port control_status iWrite_n write_n Input 1
add_interface_port control_status iAddress address Input ADDR_WIDTH
add_interface_port control_status iData writedata Input DATA_WIDTH
add_interface_port control_status oData readdata Output DATA_WIDTH
add_interface_port control_status iRead_n read_n Input 1
set_interface_assignment control_status embeddedsw.configuration.isFlash 0
set_interface_assignment control_status embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control_status embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control_status embeddedsw.configuration.isPrintableDevice 0


# 
# connection point system_clock
# 
add_interface system_clock clock end
set_interface_property system_clock clockRate 0
set_interface_property system_clock ENABLED true
set_interface_property system_clock EXPORT_OF ""
set_interface_property system_clock PORT_NAME_MAP ""
set_interface_property system_clock CMSIS_SVD_VARIABLES ""
set_interface_property system_clock SVD_ADDRESS_GROUP ""

add_interface_port system_clock iClk clk Input 1

