# TCL File Generated by Component Editor 18.1
# Sat Sep 28 17:09:10 ICT 2019
# DO NOT MODIFY


# 
# RSA "RSA" v1.0
#  2019.09.28.17:09:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module RSA
# 
set_module_property DESCRIPTION ""
set_module_property NAME RSA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME RSA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RSA_Controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Add1024.v VERILOG PATH ip/RSA/Add1024.v
add_fileset_file CheckTotalZero.v VERILOG PATH ip/RSA/CheckTotalZero.v
add_fileset_file CheckZero2048.v VERILOG PATH ip/RSA/CheckZero2048.v
add_fileset_file Compare1024.v VERILOG PATH ip/RSA/Compare1024.v
add_fileset_file Compare2048.v VERILOG PATH ip/RSA/Compare2048.v
add_fileset_file ControlMul1024.v VERILOG PATH ip/RSA/ControlMul1024.v
add_fileset_file FIFO.v VERILOG PATH ip/RSA/FIFO.v
add_fileset_file Invert1024.v VERILOG PATH ip/RSA/Invert1024.v
add_fileset_file Invert2048.v VERILOG PATH ip/RSA/Invert2048.v
add_fileset_file Mod2048.v VERILOG PATH ip/RSA/Mod2048.v
add_fileset_file ModPower1024.v VERILOG PATH ip/RSA/ModPower1024.v
add_fileset_file ModShiftRegX2048.v VERILOG PATH ip/RSA/ModShiftRegX2048.v
add_fileset_file ModShiftRegY2048.v VERILOG PATH ip/RSA/ModShiftRegY2048.v
add_fileset_file MonModInverse1024.v VERILOG PATH ip/RSA/MonModInverse1024.v
add_fileset_file MonPro1024.v VERILOG PATH ip/RSA/MonPro1024.v
add_fileset_file Mul1024bit.v VERILOG PATH ip/RSA/Mul1024bit.v
add_fileset_file PowModMon1024.v VERILOG PATH ip/RSA/PowModMon1024.v
add_fileset_file RSA_Controller.v VERILOG PATH ip/RSA/RSA_Controller.v TOP_LEVEL_FILE
add_fileset_file Sub1024.v VERILOG PATH ip/RSA/Sub1024.v
add_fileset_file Sub2048.v VERILOG PATH ip/RSA/Sub2048.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point master_write
# 
add_interface master_write avalon start
set_interface_property master_write addressUnits SYMBOLS
set_interface_property master_write associatedClock system_clock
set_interface_property master_write associatedReset reset
set_interface_property master_write bitsPerSymbol 8
set_interface_property master_write burstOnBurstBoundariesOnly false
set_interface_property master_write burstcountUnits WORDS
set_interface_property master_write doStreamReads false
set_interface_property master_write doStreamWrites false
set_interface_property master_write holdTime 0
set_interface_property master_write linewrapBursts false
set_interface_property master_write maximumPendingReadTransactions 0
set_interface_property master_write maximumPendingWriteTransactions 0
set_interface_property master_write readLatency 0
set_interface_property master_write readWaitTime 1
set_interface_property master_write setupTime 0
set_interface_property master_write timingUnits Cycles
set_interface_property master_write writeWaitTime 0
set_interface_property master_write ENABLED true
set_interface_property master_write EXPORT_OF ""
set_interface_property master_write PORT_NAME_MAP ""
set_interface_property master_write CMSIS_SVD_VARIABLES ""
set_interface_property master_write SVD_ADDRESS_GROUP ""

add_interface_port master_write oAddress_Master_Write address Output 32
add_interface_port master_write oData_Master_Write writedata Output 32
add_interface_port master_write oWrite_Master_Write write Output 1
add_interface_port master_write iWait_Master_Write waitrequest Input 1


# 
# connection point system_clock
# 
add_interface system_clock clock end
set_interface_property system_clock clockRate 0
set_interface_property system_clock ENABLED true
set_interface_property system_clock EXPORT_OF ""
set_interface_property system_clock PORT_NAME_MAP ""
set_interface_property system_clock CMSIS_SVD_VARIABLES ""
set_interface_property system_clock SVD_ADDRESS_GROUP ""

add_interface_port system_clock iSys_clk clk Input 1


# 
# connection point rsa_clock
# 
add_interface rsa_clock clock end
set_interface_property rsa_clock clockRate 0
set_interface_property rsa_clock ENABLED true
set_interface_property rsa_clock EXPORT_OF ""
set_interface_property rsa_clock PORT_NAME_MAP ""
set_interface_property rsa_clock CMSIS_SVD_VARIABLES ""
set_interface_property rsa_clock SVD_ADDRESS_GROUP ""

add_interface_port rsa_clock iRSA_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock system_clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset iRstn reset_n Input 1


# 
# connection point control_status
# 
add_interface control_status avalon end
set_interface_property control_status addressUnits WORDS
set_interface_property control_status associatedClock system_clock
set_interface_property control_status associatedReset reset
set_interface_property control_status bitsPerSymbol 8
set_interface_property control_status burstOnBurstBoundariesOnly false
set_interface_property control_status burstcountUnits WORDS
set_interface_property control_status explicitAddressSpan 0
set_interface_property control_status holdTime 0
set_interface_property control_status linewrapBursts false
set_interface_property control_status maximumPendingReadTransactions 0
set_interface_property control_status maximumPendingWriteTransactions 0
set_interface_property control_status readLatency 0
set_interface_property control_status readWaitTime 1
set_interface_property control_status setupTime 0
set_interface_property control_status timingUnits Cycles
set_interface_property control_status writeWaitTime 0
set_interface_property control_status ENABLED true
set_interface_property control_status EXPORT_OF ""
set_interface_property control_status PORT_NAME_MAP ""
set_interface_property control_status CMSIS_SVD_VARIABLES ""
set_interface_property control_status SVD_ADDRESS_GROUP ""

add_interface_port control_status iChipSelect_Control chipselect Input 1
add_interface_port control_status iWrite_Control write Input 1
add_interface_port control_status iRead_Control read Input 1
add_interface_port control_status iAddress_Control address Input 3
add_interface_port control_status iData_Control writedata Input 32
add_interface_port control_status oData_Control readdata Output 32
set_interface_assignment control_status embeddedsw.configuration.isFlash 0
set_interface_assignment control_status embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control_status embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control_status embeddedsw.configuration.isPrintableDevice 0


# 
# connection point master_read
# 
add_interface master_read avalon start
set_interface_property master_read addressUnits SYMBOLS
set_interface_property master_read associatedClock system_clock
set_interface_property master_read associatedReset reset
set_interface_property master_read bitsPerSymbol 8
set_interface_property master_read burstOnBurstBoundariesOnly false
set_interface_property master_read burstcountUnits WORDS
set_interface_property master_read doStreamReads false
set_interface_property master_read doStreamWrites false
set_interface_property master_read holdTime 0
set_interface_property master_read linewrapBursts false
set_interface_property master_read maximumPendingReadTransactions 0
set_interface_property master_read maximumPendingWriteTransactions 0
set_interface_property master_read readLatency 0
set_interface_property master_read readWaitTime 1
set_interface_property master_read setupTime 0
set_interface_property master_read timingUnits Cycles
set_interface_property master_read writeWaitTime 0
set_interface_property master_read ENABLED true
set_interface_property master_read EXPORT_OF ""
set_interface_property master_read PORT_NAME_MAP ""
set_interface_property master_read CMSIS_SVD_VARIABLES ""
set_interface_property master_read SVD_ADDRESS_GROUP ""

add_interface_port master_read oAddress_Master_Read address Output 32
add_interface_port master_read oRead_Master_Read read Output 1
add_interface_port master_read iDataValid_Master_Read readdatavalid Input 1
add_interface_port master_read iWait_Master_Read waitrequest Input 1
add_interface_port master_read iReadData_Master_Read readdata Input 32

