	soc_system u0 (
		.button_pio_external_connection_export (<connected-to-button_pio_external_connection_export>), // button_pio_external_connection.export
		.clk_clk                               (<connected-to-clk_clk>),                               //                            clk.clk
		.dipsw_pio_external_connection_export  (<connected-to-dipsw_pio_external_connection_export>),  //  dipsw_pio_external_connection.export
		.hps_0_f2h_cold_reset_req_reset_n      (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),      //       hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n     (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),     //      hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_stm_hw_events_stm_hwevents  (<connected-to-hps_0_f2h_stm_hw_events_stm_hwevents>),  //        hps_0_f2h_stm_hw_events.stm_hwevents
		.hps_0_f2h_warm_reset_req_reset_n      (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),      //       hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_reset_reset_n               (<connected-to-hps_0_h2f_reset_reset_n>),               //                hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>), //                   hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),   //                               .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),   //                               .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),   //                               .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),   //                               .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),   //                               .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),   //                               .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),    //                               .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>), //                               .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>), //                               .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>), //                               .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),   //                               .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),   //                               .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),   //                               .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_qspi_inst_IO0     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO0>),     //                               .hps_io_qspi_inst_IO0
		.hps_0_hps_io_hps_io_qspi_inst_IO1     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO1>),     //                               .hps_io_qspi_inst_IO1
		.hps_0_hps_io_hps_io_qspi_inst_IO2     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO2>),     //                               .hps_io_qspi_inst_IO2
		.hps_0_hps_io_hps_io_qspi_inst_IO3     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO3>),     //                               .hps_io_qspi_inst_IO3
		.hps_0_hps_io_hps_io_qspi_inst_SS0     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_SS0>),     //                               .hps_io_qspi_inst_SS0
		.hps_0_hps_io_hps_io_qspi_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_CLK>),     //                               .hps_io_qspi_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),     //                               .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),      //                               .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),      //                               .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),     //                               .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),      //                               .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),      //                               .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),      //                               .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),      //                               .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),      //                               .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),      //                               .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),      //                               .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),      //                               .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),      //                               .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),      //                               .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),     //                               .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),     //                               .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),     //                               .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),     //                               .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim0_inst_CLK    (<connected-to-hps_0_hps_io_hps_io_spim0_inst_CLK>),    //                               .hps_io_spim0_inst_CLK
		.hps_0_hps_io_hps_io_spim0_inst_MOSI   (<connected-to-hps_0_hps_io_hps_io_spim0_inst_MOSI>),   //                               .hps_io_spim0_inst_MOSI
		.hps_0_hps_io_hps_io_spim0_inst_MISO   (<connected-to-hps_0_hps_io_hps_io_spim0_inst_MISO>),   //                               .hps_io_spim0_inst_MISO
		.hps_0_hps_io_hps_io_spim0_inst_SS0    (<connected-to-hps_0_hps_io_hps_io_spim0_inst_SS0>),    //                               .hps_io_spim0_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),     //                               .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),     //                               .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),     //                               .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),     //                               .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),     //                               .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),     //                               .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),  //                               .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),  //                               .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO37  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO37>),  //                               .hps_io_gpio_inst_GPIO37
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),  //                               .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO41  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO41>),  //                               .hps_io_gpio_inst_GPIO41
		.hps_0_hps_io_hps_io_gpio_inst_GPIO44  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO44>),  //                               .hps_io_gpio_inst_GPIO44
		.hps_0_hps_io_hps_io_gpio_inst_GPIO48  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO48>),  //                               .hps_io_gpio_inst_GPIO48
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),  //                               .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),  //                               .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),  //                               .hps_io_gpio_inst_GPIO61
		.hps_0_i2c2_out_data                   (<connected-to-hps_0_i2c2_out_data>),                   //                     hps_0_i2c2.out_data
		.hps_0_i2c2_sda                        (<connected-to-hps_0_i2c2_sda>),                        //                               .sda
		.hps_0_i2c2_clk_clk                    (<connected-to-hps_0_i2c2_clk_clk>),                    //                 hps_0_i2c2_clk.clk
		.hps_0_i2c2_scl_in_clk                 (<connected-to-hps_0_i2c2_scl_in_clk>),                 //              hps_0_i2c2_scl_in.clk
		.hps_0_spim1_txd                       (<connected-to-hps_0_spim1_txd>),                       //                    hps_0_spim1.txd
		.hps_0_spim1_rxd                       (<connected-to-hps_0_spim1_rxd>),                       //                               .rxd
		.hps_0_spim1_ss_in_n                   (<connected-to-hps_0_spim1_ss_in_n>),                   //                               .ss_in_n
		.hps_0_spim1_ssi_oe_n                  (<connected-to-hps_0_spim1_ssi_oe_n>),                  //                               .ssi_oe_n
		.hps_0_spim1_ss_0_n                    (<connected-to-hps_0_spim1_ss_0_n>),                    //                               .ss_0_n
		.hps_0_spim1_ss_1_n                    (<connected-to-hps_0_spim1_ss_1_n>),                    //                               .ss_1_n
		.hps_0_spim1_ss_2_n                    (<connected-to-hps_0_spim1_ss_2_n>),                    //                               .ss_2_n
		.hps_0_spim1_ss_3_n                    (<connected-to-hps_0_spim1_ss_3_n>),                    //                               .ss_3_n
		.hps_0_spim1_sclk_out_clk              (<connected-to-hps_0_spim1_sclk_out_clk>),              //           hps_0_spim1_sclk_out.clk
		.hps_0_spis1_txd                       (<connected-to-hps_0_spis1_txd>),                       //                    hps_0_spis1.txd
		.hps_0_spis1_rxd                       (<connected-to-hps_0_spis1_rxd>),                       //                               .rxd
		.hps_0_spis1_ss_in_n                   (<connected-to-hps_0_spis1_ss_in_n>),                   //                               .ss_in_n
		.hps_0_spis1_ssi_oe_n                  (<connected-to-hps_0_spis1_ssi_oe_n>),                  //                               .ssi_oe_n
		.hps_0_spis1_sclk_in_clk               (<connected-to-hps_0_spis1_sclk_in_clk>),               //            hps_0_spis1_sclk_in.clk
		.hps_0_uart1_cts                       (<connected-to-hps_0_uart1_cts>),                       //                    hps_0_uart1.cts
		.hps_0_uart1_dsr                       (<connected-to-hps_0_uart1_dsr>),                       //                               .dsr
		.hps_0_uart1_dcd                       (<connected-to-hps_0_uart1_dcd>),                       //                               .dcd
		.hps_0_uart1_ri                        (<connected-to-hps_0_uart1_ri>),                        //                               .ri
		.hps_0_uart1_dtr                       (<connected-to-hps_0_uart1_dtr>),                       //                               .dtr
		.hps_0_uart1_rts                       (<connected-to-hps_0_uart1_rts>),                       //                               .rts
		.hps_0_uart1_out1_n                    (<connected-to-hps_0_uart1_out1_n>),                    //                               .out1_n
		.hps_0_uart1_out2_n                    (<connected-to-hps_0_uart1_out2_n>),                    //                               .out2_n
		.hps_0_uart1_rxd                       (<connected-to-hps_0_uart1_rxd>),                       //                               .rxd
		.hps_0_uart1_txd                       (<connected-to-hps_0_uart1_txd>),                       //                               .txd
		.i2c_0_i2c_serial_sda_in               (<connected-to-i2c_0_i2c_serial_sda_in>),               //               i2c_0_i2c_serial.sda_in
		.i2c_0_i2c_serial_scl_in               (<connected-to-i2c_0_i2c_serial_scl_in>),               //                               .scl_in
		.i2c_0_i2c_serial_sda_oe               (<connected-to-i2c_0_i2c_serial_sda_oe>),               //                               .sda_oe
		.i2c_0_i2c_serial_scl_oe               (<connected-to-i2c_0_i2c_serial_scl_oe>),               //                               .scl_oe
		.i2c_master_0_scl_export               (<connected-to-i2c_master_0_scl_export>),               //               i2c_master_0_scl.export
		.i2c_master_0_sda_export               (<connected-to-i2c_master_0_sda_export>),               //               i2c_master_0_sda.export
		.i2c_slave_0_scl_export                (<connected-to-i2c_slave_0_scl_export>),                //                i2c_slave_0_scl.export
		.i2c_slave_0_sda_export                (<connected-to-i2c_slave_0_sda_export>),                //                i2c_slave_0_sda.export
		.led_pio_external_connection_export    (<connected-to-led_pio_external_connection_export>),    //    led_pio_external_connection.export
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //                         memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                               .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                               .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                               .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                               .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                               .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                               .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                               .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                               .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                               .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                               .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                               .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                               .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                               .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                               .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                               .oct_rzqin
		.reset_reset_n                         (<connected-to-reset_reset_n>),                         //                          reset.reset_n
		.reset_0_reset_n                       (<connected-to-reset_0_reset_n>),                       //                        reset_0.reset_n
		.spi_0_external_MISO                   (<connected-to-spi_0_external_MISO>),                   //                 spi_0_external.MISO
		.spi_0_external_MOSI                   (<connected-to-spi_0_external_MOSI>),                   //                               .MOSI
		.spi_0_external_SCLK                   (<connected-to-spi_0_external_SCLK>),                   //                               .SCLK
		.spi_0_external_SS_n                   (<connected-to-spi_0_external_SS_n>),                   //                               .SS_n
		.spi_cores_0_spi_miso_export           (<connected-to-spi_cores_0_spi_miso_export>),           //           spi_cores_0_spi_miso.export
		.spi_cores_0_spi_mosi_export           (<connected-to-spi_cores_0_spi_mosi_export>),           //           spi_cores_0_spi_mosi.export
		.spi_cores_0_spi_sck_export            (<connected-to-spi_cores_0_spi_sck_export>),            //            spi_cores_0_spi_sck.export
		.spi_cores_0_spi_ss_export             (<connected-to-spi_cores_0_spi_ss_export>),             //             spi_cores_0_spi_ss.export
		.ssp_uart_avalon_0_rxd_232_export      (<connected-to-ssp_uart_avalon_0_rxd_232_export>),      //      ssp_uart_avalon_0_rxd_232.export
		.ssp_uart_avalon_0_rxd_485_export      (<connected-to-ssp_uart_avalon_0_rxd_485_export>),      //      ssp_uart_avalon_0_rxd_485.export
		.ssp_uart_avalon_0_txd_232_export      (<connected-to-ssp_uart_avalon_0_txd_232_export>),      //      ssp_uart_avalon_0_txd_232.export
		.ssp_uart_avalon_0_txd_485_export      (<connected-to-ssp_uart_avalon_0_txd_485_export>),      //      ssp_uart_avalon_0_txd_485.export
		.ssp_uart_avalon_0_xcts_export         (<connected-to-ssp_uart_avalon_0_xcts_export>),         //         ssp_uart_avalon_0_xcts.export
		.ssp_uart_avalon_0_xde_export          (<connected-to-ssp_uart_avalon_0_xde_export>),          //          ssp_uart_avalon_0_xde.export
		.ssp_uart_avalon_0_xrts_export         (<connected-to-ssp_uart_avalon_0_xrts_export>),         //         ssp_uart_avalon_0_xrts.export
		.uart_0_external_connection_rxd        (<connected-to-uart_0_external_connection_rxd>),        //     uart_0_external_connection.rxd
		.uart_0_external_connection_txd        (<connected-to-uart_0_external_connection_txd>),        //                               .txd
		.uart_clock_clk                        (<connected-to-uart_clock_clk>)                         //                     uart_clock.clk
	);

